name: release
on:
  schedule:
    - cron: "0 0 * * *" # midnight UTC

  workflow_dispatch:

  push:
    branches:
      - release
      - trigger-nightly

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -W unreachable-pub"
  RUSTUP_MAX_RETRIES: 10
  FETCH_DEPTH: 0 # pull in the tags for the version string
  MACOSX_DEPLOYMENT_TARGET: 14.0
  ZIG_VERSION: 0.13.0
  ZIGBUILD_VERSION: 0.19.8

jobs:
  publish:
    if: ${{ github.repository == 'rust-lang/rust-analyzer' || github.event_name == 'workflow_dispatch' }}
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Set release tag
        run: |
          if [ "${{ github.ref }}" = "refs/heads/release" ]; then
            git fetch --tags
            today=$(date --iso -u)
            last_tag=$(git tag -l "${today}*" | sort -V | tail -n1)
            if [ -n "$last_tag" ]; then
              last_v=$(echo "$last_tag" | grep -oP '(?<=\.)\d+' || echo 0)
              new_v=$(($last_v + 1))
              tag="${today}.${new_v}"
            else
              tag="$today"
            fi
            echo "TAG=$tag" >> $GITHUB_ENV
          else
            echo "TAG=nightly" >> $GITHUB_ENV
          fi

      - run: echo "HEAD_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - run: 'echo "HEAD_SHA: $HEAD_SHA"'

      - name: Publish Release
        uses: ./.github/actions/github-release
        with:
          files: "dist/*"
          name: ${{ env.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
